install: true

sudo: false

services:
  - docker

before_script:
  - git checkout $TRAVIS_BRANCH
  - git submodule update --remote

script:
  - docker build -t appdax/finnet-fetcher:test -f Dockerfile.test .
  - docker run -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN -t appdax/finnet-fetcher:test
  - docker rmi -f appdax/finnet-fetcher:test
  - docker build -t appdax/finnet-fetcher:edge -f Dockerfile .
  - docker ps -a
  - docker images --filter "dangling=false"

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push appdax/finnet-fetcher
