language: ruby

sudo: required

services:
  - docker

rvm:
  - 2.2
matrix:
  fast_finish: true

before_install:
  - bundle install
bundler_args: --without development
cache: bundler

script:
  - bundle exec rake
  - docker build -t appdax/finnet-fetcher:edge .
  - docker ps -a
  - docker images --filter "dangling=false"
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push appdax/finnet-fetcher
