language: ruby

sudo: required

services:
  - docker

rvm:
  - 2.2
  - 2.3.0
matrix:
  allow_failures:
    - rvm: 2.3.0
  fast_finish: true

before_install:
  - bundle install
bundler_args: --without development
cache: bundler

script:
  - bundle exec rake
  - docker build -t appdax-finnet-fetcher
  - docker ps -a
